### ISSUE TITLE
Shop dropdown should only show if I have/manage multiple shops

### ISSUE THREAD

**Issue by cindyfirestone** [reactioncommerce/reaction-admin#116]
### Expected behavior
The dropdown to switch between shops should only exist if I manage multiple shops. 

### Actual behavior
The dropdown always shows up, even if I only manage one shop and there is one item in the drop down. 

![home](https://user-images.githubusercontent.com/22083616/32241175-b2d2c0c2-be2c-11e7-8a59-71e7588d40e0.png)

**Comment by aldeed** [comment]
Closing this since currently there is no shop dropdown
