### ISSUE TITLE
Convert Update Password from Blaze to React

### ISSUE THREAD

**Issue by tom-gerken** [reactioncommerce/reaction-admin#119]
Convert the `updatePassword.html` and `updatePassword.js` panel in `import/plugins/core/account/client/templates/updatePassword` to React

Part of reactioncommerce/reaction#3203 

This appears in the Account panel

![2018-03-01_08-18-33](https://user-images.githubusercontent.com/72819/36820524-2b7951de-1d29-11e8-8dd5-03c93773ee70.png)

**Comment by aldeed** [comment]
This was moved to Reaction Identity project and modernized
