### ISSUE TITLE
[v3.0.0] Cannot set price for variants

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction-admin#170]
## Issue Description
Setting and publishing the price for a variant does not take effect.
<img src="http://g.recordit.co/jNNidHAv2s.gif" />
No errors are reported. This is different than #91
Viewing the product in a storefront will also show the product without a price.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Create a new variant.
2. Add a price to it
3. Refresh to see that the price is reset to zero.

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug

### Versions
release-3.0.0

**Comment by spencern** [comment]
Update after #166 was merged - I'm still seeing this issue.

**Comment by aldeed** [comment]
API side issue is https://github.com/reactioncommerce/reaction/issues/5916

https://github.com/reactioncommerce/reaction/pull/5910 adds a way to set the price but we haven't yet updated the admin UI to use it.
