### ISSUE TITLE
[v3.0.0] Unable to see newly added tag from Tags page

### ISSUE THREAD

**Issue by trojanh** [reactioncommerce/reaction-admin#177]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
When creating a tag from Tags page, the tag gets created in DB but doesn't show on the Tags list.
When creating tag from Product page, the tag shows on Tags page.

I verified the same query using the Apollo client and it shows all the tag.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Navigate to `Tags` page, i.e `http://localhost:4080/tags`
2. Create new Tag by clicking on `Create a tag`, 
3. Navigate back to `Tags` page and you cannot see the tag you just created.

Only Tags created from the Product page are visible.

## Possible Solution
Something to do with meteor taken bases tag fetching, need to debug more.

### Versions
3.0.0-alpha

**Comment by trojanh** [comment]
I noticed this after some debugging:

- The Tags page shows only visible tags, when we create a new Tag from Tags page its `isVisible: false` by default. So it's not fetched on the Tags page.
- I tried sending `shouldIncludeInvisible: true` in request but still couldn't get invisible tags.
- Normal Apollo playground request shows all the tags without any additional variables in the request.

I was trying to intercept the `Tags` query but `console.log` statements are not working on API server. I even tried `REACTION_LOG_LEVEL=TRACE` in env but the server doesn't show any log statements. 

I think [this particular condition](https://github.com//reactioncommerce/reaction/blob/26a584eb6fbafdc0baf83d9bbbc8a7531393431a/src/core-services/tags/queries/tags.js#L79) might be causing the issue but will need to figure out a way to let API server show console.logs to be sure. 

@aldeed any leads would be appreciated. Thanks

**Comment by aldeed** [comment]
@trojanh I noticed this, too, but hadn't investigated yet. Good initial research!

Looking at the code, line 78 looks wrong to me. I think it should start with `if (!hasInactivePermissions` (add exclamation), like line 71 does.

If you add that and then include `shouldIncludeInvisible: true` in GraphQL request, does that fix it?

**Comment by trojanh** [comment]
@aldeed Initially, when I made that change I couldn't be sure if those changes were actually getting reflected on `api` server as `console.log`s were not working and there was no sign of server restart after making the change in server logs, so I restarted the server and I could still not see it working.

So all tags were not getting fetched after making that change on api and passing `shouldIncludeInvisible: true` from admin.

**Comment by trojanh** [comment]
@aldeed that fix is working and I can verify that. 

I came across this issue https://github.com/reactioncommerce/reaction-platform/issues/83 which was causing me to use the `published image` of reaction by default which I didn't notice initially. 

I will raise a PR for this issue.
