### ISSUE TITLE
[v.3.0.0] Full GQL coverage on product editor

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction-admin#184]
There are various issues with the product editor that make it a poor experience. The main cause of this is the use of Meteor and GQL simultaneously for editing which causes sluggish controls and incorrect data display.

In this refactor

- Update to use only GQL, no meteor.
- Update components to use Component Library / Catalyst (current components may rely too much on meteor)

Related Tickets:
https://github.com/reactioncommerce/reaction-admin/issues/68
https://github.com/reactioncommerce/reaction-admin/issues/169

**Comment by HarisSpahija** [comment]
Is there a chance that the components can make use of Material UI instead of the component library/catalyst? It is more mainstream and clearer for users on how to use those libraries than the existing ones.
