### ISSUE TITLE
Can't select Origin Country when creating a product

### ISSUE THREAD

**Issue by brent-hoover** [reactioncommerce/reaction-admin#186]
## Issue Description
Providing a clear description of the issue will enable a developer to quickly reproduce and understand the issue. Please provide a detailed description including images, animation and/or videos. For client issues, include browser console errors, for server issues please add terminal output and stack traces.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Begin creating a product
2. Select a country from the "Origin Country" dropdown
3. Observe that the value does not change

### Versions
`release-v3.0.0-beta`

**Comment by jrw421** [comment]
Hi @zenweasel! We weren't able to reproduce this bug, so I'll be closing it out. Please feel free to reopen the issue with detailed steps should you continue to see this on your end. Thanks!
