### ISSUE TITLE
Update autoforms to use graphql mutations for shop settings

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction-admin#202]
With the removal of the `Security` meteor package, any `autoform` forms left in the codebase no longer work. These should all be updated to new form fields that use GraphQL for their mutations.

autoforms remaining, in order of most importance to update:

- [ ] Shop Settings (https://github.com/reactioncommerce/reaction-admin/blob/trunk/imports/plugins/core/dashboard/client/templates/shop/settings/settings.html#L19:L19) & (https://github.com/reactioncommerce/reaction-admin/blob/trunk/imports/plugins/core/dashboard/client/templates/shop/settings/settings.html#L46:L46)

The mutations for these forms already exist, therefore this is not a blocker for 3.0, but a nice-to-have for the `reaction-admin`.

Once these are removed, we can remove the `aldeed:autoform` package.

**Comment by willopez** [comment]
breaking issue into multiple issues:
https://github.com/reactioncommerce/reaction-admin/issues/227
https://github.com/reactioncommerce/reaction-admin/issues/226
https://github.com/reactioncommerce/reaction-admin/issues/229
