### ISSUE TITLE
System tries to create Primary Shop twice on startup

### ISSUE THREAD

**Issue by brent-hoover** [reactioncommerce/reaction-admin#210]
## Issue Description
One first user creation the system prompts you to create your first shop. After entering the shop name it asks you for a shop name a second time and then errors out because you can't create two primary shops.

```
api_1    | 02:32:34.828Z ERROR Reaction: Error sending welcome email but account was created
api_1    |   ReactionError: Shop not found
api_1    |       at sendWelcomeEmail (file:///usr/local/src/app/src/core-services/account/util/sendWelcomeEmail.js:49:20)
api_1    |       at runMicrotasks (<anonymous>)
api_1    |       at processTicksAndRejections (internal/process/task_queues.js:94:5)
api_1    |       at async Object.createAccount (file:///usr/local/src/app/src/core-services/account/mutations/createAccount.js:120:5)
api_1    |       at async buildContext (file:///usr/local/src/app/src/core/util/buildContext.js:67:19)
api_1    |       at async ApolloServer.context (file:///usr/local/src/app/src/core/createApolloServer.js:60:7)
api_1    | 02:32:53.165Z ERROR Reaction: There may be only one primary shop (errorId=ck6a4lsq500000ir8dsc7eo74)
api_1    |   path: [
api_1    |     "createShop"
api_1    |   ]
api_1    |   --
api_1    |   stack: ReactionError: There may be only one primary shop
api_1    |       at Object.createShop (file:///usr/local/src/app/src/core-services/shop/mutations/createShop.js:115:13)
api_1    |       at runMicrotasks (<anonymous>)
api_1    |       at processTicksAndRejections (internal/process/task_queues.js:94:5)
api_1    |       at async createShop (file:///usr/local/src/app/src/core-services/shop/resolvers/Mutation/createShop.js:19:16)
```

## Steps to Reproduce
1. Run a fresh clone/version of platform with no db
2. Create the first account
3. Observe that you are prompted to create a shop twice
4. Observe the error in the api server console.

### Versions
`release-3.0.0-beta.3` Hash: `cee2161c6`

**Comment by brent-hoover** [comment]
This appears to be a timing thing. If you wait long enough after creating the first shop, it continues onto the admin as normal. But right now it rerenders the "Create a shop" form right after input.

**Comment by brent-hoover** [comment]
Actually from the home screen every time you refresh it briefly shows the "Create a Shop" prompt and then removes it.

**Comment by aldeed** [comment]
Yes the lack of a loading indicator and the brief flashing are known issues but they're virtually impossible to solve (as far as I could tell) due to the many layers of Meteor and routing historical code. Instead of worrying about this, we will hopefully finish transitioning the remaining old things and rip out all of the layers in favor of a clean new router and state paradigm.
