### ISSUE TITLE
MUI warning about `makeStyles` in console

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction-admin#219]
## Issue

I’m seeing warnings from the new settings in the console

```
It looks like there are several instances of `@material-ui/styles` initialized in this application.
This may cause theme propagation issues, broken class names, specificity issues, and makes your application bigger without a good reason.

See https://material-ui.com/r/styles-instance-warning for more info.
```

## Solution

`import { makeStyles } from "@material-ui/core";`

instead of

`import { makeStyles } from "@material-ui/styles";`

`@material-ui/styles` is better suited if you want to use MUI's theme framework outside of MUI. All imports related to styles are also exposed in `@material-ui/core` and are set up to work with the core lib.

**Comment by jrw421** [comment]
Hi @mikemurray! Took a look through the codebase and looks like this change has already been made and the error is no longer present in the console. Going to go ahead and close it out, but please create another issue if you continue to see this warning. Thanks!
