### ISSUE TITLE
Convert Profile panel to React

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction-admin#222]
The panel reachable from the Account dropdown which includes the Updatepassword and CompletedOrders and address panel

![2018-03-01_08-32-24](https://user-images.githubusercontent.com/72819/36820880-2032f684-1d2b-11e8-9140-50fe55f50bc4.png)

**Comment by brent-hoover** [comment]
Yeah, this guy gets it

Actually what I was referencing here was the Account panel that's accessible to Consumers that I don't think exists in `example-storefront` because it was "feature reduced" in the GraphQL conversion
