### ISSUE TITLE
Refactor template settings form to use the GraphQL API

### ISSUE THREAD

**Issue by willopez** [reactioncommerce/reaction-admin#227]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
The template settings form depends on Meteor, remove that dependency by using the GraphQL API

Template settings (https://github.com/reactioncommerce/reaction-admin/blob/trunk/imports/plugins/core/templates/client/templates/settings.html#L14:L14)

**Comment by loan-laux** [comment]
I'll take this one if no one is already on it.

**Comment by willopez** [comment]
@loan-laux sure, go for it.

**Comment by loan-laux** [comment]
@willopez Done. Feel free to take a look when you have time.

**Comment by willopez** [comment]
@loan-laux an OSS team member will be reviewing.

**Comment by loan-laux** [comment]
Thanks @willopez!
