### ISSUE TITLE
Audit settings and remove settings that are not longer functional. 

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction-admin#228]
A number of our settings panels no longer work or no longer relevant. This issue is a placeholder to audit these and remove those that are no longer applicable.

**Comment by rymorgan** [comment]
@cassytaylor Can you add the notes of the updates from our meeting to this issue?

**Comment by cassytaylor** [comment]
- SHOP
    - We need to rewrite the helper text copy 
    - Should “Inventory” be its own setting or under something else?
    - Sitemaps: should there be another SEO page that this would go under (or should it go under Email too?)
    - Storefront URLs is template variables for emails - could it be combined under Template page (which could be renamed Email/etc?)
- EMAIL - consolidate all email things here
    - Add Templates 
    - Add Storefront URLs - (“Email URLs”, “Template URLs”, “URL Variables etc.”)
- PAYMENT
    - Payment is now enable/disable for IOU example and Stripe card… that’s it
    - Should be switches/toggles
- TAXES
    - Looks good
- ADDRESS VALIDATION 
    - On its own page now
- SYSTEM INFORMATION
    - On its own page now

**Comment by rymorgan** [comment]
What we're doing now -- 

**Consolidating email-related settings.** 
- [x] Move templates from settings navigation to a card under email. (these are only used for email)
- [x] Move storefront URLs from shop settings to email. 
- [x] @cassytaylor Will provide design for the whole email settings view 

- [x] **Reordering the settings menu** 

Here's the order 
Shop
Payment 
Taxes 
Shipping
Email 
Shop localization 
Address validation 
System information 

*note these should sentence case not title case 

- [x] **Add toggle for payment enable/disable**

**Comment by rymorgan** [comment]
@willopez The two pieces I don't see competed here are - the payment toggles and email templates. Oh and the settings menu should be sentence case.

**Comment by ghost** [comment]
I enabled Stripe Card in the settings and then tried to check out using the example storefront. That didn't work, so I checked the documentation at https://docs.reactioncommerce.com/docs/core-plugins-stripe

> There are two settings fields you need to fill out for Stripe to work, API Secret Key and Publishable Key. Copy these from your Stripe account, and paste them into the fields. 

The documentation seems out of date, as the settings fields are no longer there. How do I set up Stripe?
