### ISSUE TITLE
Multi-site installations not supported

### ISSUE THREAD

**Issue by loan-laux** [reactioncommerce/reaction-admin#234]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
While the Reaction API supports multi-sites (and with some custom work, multi-vendor marketplaces), `reaction-admin` always falls back to the primary shop in `Reaction.getCurrentShop()`, making it incompatible with such setups.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Create a primary shop with user `A`
2. Create a secondary shop with user `B`
3. Try to log in as user `B`
4. See that you're shown the admin panel for the primary shop (where it should have been the secondary one, which you had created)

## Possible Solution
Introduce an environment variable to optimize for multi-site scenarios. When set to true, `reaction-admin` will not fall back to the primary shop and will instead enforce whatever `activeShopId` the user has in their profile.

With this solution, there will be no changes to the experience for single-vendor/single-site setups. It will enable developers to offer marketplace/multi-sites plugins and have the core of their features supported in a clean manner out of the box.

### Versions
```
3.0.0-beta.5
```

**Comment by aldeed** [comment]
@loan-laux Do you agree this could be closed to centralize all multi-shop and shop selector discussion in https://github.com/reactioncommerce/reaction-admin/issues/93?

**Comment by loan-laux** [comment]
Absolutely! Closing now.
