### ISSUE TITLE
Revisit product media gallery editor

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction-admin#236]
## Issues

Issues that arise from the new product editor from this PR: https://github.com/reactioncommerce/reaction-admin/pull/188

- [x] Reloading data after uploading an image doesn't work due to the delay from upload to converting and saving with sharp. https://github.com/reactioncommerce/reaction-admin/pull/188#issuecomment-594101238
- [x] The display of the media might be inaccurate. The product may be showing images from the variants as well.

- [x] Priority field doesn't work

**Comment by janus-reith** [comment]
Second issue here needs to be solved in `reaction-api`.
`getProductMedia` in the Products resolver needs an adapted db query where `variantId` should be `null` or not exist.
For the ProductVariant resolver there currently is no media resolver, threfore a `getVariantMedia` function needs to be crated which does the same thing as `getProductMedia`  but queries by `variantId`

**Comment by janus-reith** [comment]
Media Priority can't be changed in ProductMediaItem:

```
setPriority(() => {
              const intValue = parseInt(event.target.value, 10);
              console.log("intValue", intValue);
              return {
                priority: isInteger(intValue) ? intValue : null
              };
});
```

This should return the value, not an object with key `priority`.

Also, Ids would need to be encoded for media actions like priority change, remove, etc an currently are not.
Might be better solution to update the api instead to only send encoded Ids instead.
