### ISSUE TITLE
Issues found with new settings pages

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction-admin#238]
- [x] Couldn't save the main shop settings form without adding a shop email. Initially, it didn't seem to give me an error. After entering the email, the forms save consistently. Even if I remove the shop email.

- [ ]  Can scroll the layout container. This is hard reproduce, and may just be a general layout issue. Double-check that no other settings subpage or template does overflow scroll other than the `ContentViewPrimaryDetailLayout` component.
![image](https://user-images.githubusercontent.com/42217/76029261-fab7e200-5ee8-11ea-829f-4f53962bd2ab.png)

- [x] Some pages need bottom padding
![image](https://user-images.githubusercontent.com/42217/76029443-54201100-5ee9-11ea-9ac1-d03e6219981e.png)

- Payment (maybe but it too short to matter)
- Taxes
- Shipping
- System information
- Address validation

Each card either needs margin-bottom, or you can do this to make it automatic
```
                <Blocks region="RegionName">
                  {(blocks) =>
                    blocks.map((block, index) => (
                      <Box paddingBottom={2} key={index}>
                        {block}
                      </Box>
                    ))
                  }
                </Blocks>
```

- [x] All "save" button should say "save changes" i18nkey "app.saveChanges". Some do, but others don't

- [x] Consider disabling save buttons if the form isn't dirty. `isDirty` is available from the `useReactoForm` hook. `disabled={!isDirty || isSubmitting}`

- [x] Cancel button in address dialog should be primary. The secondary blue pops

- [x] The loading spinners need some height.

- [x] Sidebar list should highlight the active item

**Comment by vandernorth** [comment]
Additionally: I wasn't able to open the email-logs.

**Comment by willopez** [comment]
@vandernorth can you provide more details? I see the email logs under the "Email" link
