### ISSUE TITLE
Creation of Tags only happens after refreshing the page

### ISSUE THREAD

**Issue by HarisSpahija** [reactioncommerce/reaction-admin#252]
## Prerequisites
* [X] Are you running the latest version?
* [X] Are you able to consistently reproduce the issue?
* [X] Did you search the issue queue for existing issue?

## Issue Description
When trying to create a tag inside the Tags tab, the saving visuals are displayed for a very brief moment. After going back to the tags they are not displayed untill the page gets refreshed. See streamable. 
https://streamable.com/jrvx35

## Steps to Reproduce
Be logged in as a Administrator in Reaction Admin	
1. Navigate to Tags and click "Create a Tag"
2. Fill out required fields such as Tag Name, Display Title and Slug.
3. Click on Save Changes
4. Navigate back to Tags
5. Created Tag is not visible untill refresh

## Possible Solution
Refreshing on the tag page works but is unclear for the user

### Versions
"version": "3.0.0-beta.5"

**Comment by loan-laux** [comment]
I'm experiencing this as well.

**Comment by loan-laux** [comment]
I've solved this by calling the `getTags` query with `fetchPolicy="network-only"` in [TagDataTable:470](https://github.com/reactioncommerce/reaction-admin/blob/a52ebe985361bd8e8111b2cea9a7b9ab630f88bf/imports/plugins/core/tags/client/components/TagDataTable.js#L470).

I've submitted a PR here: #254.
