### ISSUE TITLE
Can't see nor edit navigation tree

### ISSUE THREAD

**Issue by loan-laux** [reactioncommerce/reaction-admin#256]
Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
After installing a brand new Reaction Commerce environment with the latest `reaction-admin`, the "Navigation" page doesn't show a navigation tree. Navigation items are showing up fine on the left, but the right is essentially a blank area. It is thus impossible to modify anything navigation related as of now.

<img width="1467" alt="Screen Shot 2020-04-13 at 16 12 14" src="https://user-images.githubusercontent.com/45489203/79127482-44c29c00-7da2-11ea-9518-b9cf5bf036c6.png">

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Log in a user
2. Click the Navigation link in the sidebar
3. Notice that your navigation tree isn't showing up

### Versions
`3.0.0-beta.6`

**Comment by loan-laux** [comment]
@willopez, happy to assign myself if you prefer to have this off your hands. Let me know!

**Comment by willopez** [comment]
@loan-laux that would be great, thanks! 

and maybe this helps: https://github.com/frontend-collective/react-sortable-tree/issues/665

**Comment by null-ref-0000** [comment]
I experienced this bug in 3.0.0-beta.5 and 3.0.0-beta.6. I rolled back to v3.0.0-beta.3 and didn't experience the bug.
