### ISSUE TITLE
Address not matched after removing region or postal code in custom tax rate

### ISSUE THREAD

**Issue by derBretti** [reactioncommerce/reaction-admin#259]
## Issue Description
When a region or postal code is first added to a custom tax rate and then removed, the value in the database becomes "" (empty string). This causes the tax rate not to be found when calculating taxes, because the selector in calculateOrderTaxes/getTaxesForShop only matches custom taxes where the fields are either null or match to the corresponding fields in the address. 

## Steps to Reproduce
1. Add a custom tax rate leave postal code and region blank
2. Set rate to a product and publish
3. Add product to cart
4. Enter an address with matching country in checkout (note that tax is applied)
5. Edit the tax rate, set an arbitrary value for Region or Postal code
6. Edit the tax rate, delete the value for region or postal code
7. Update cart
8. Note that the tax rate is not applied to the cart anymore 

## Possible Solution
Either change selector in calculateOrderTaxes/getTaxesForShop to treat empty strings as null values
or
replace empty strings with null in reaction-admin

### Versions
3.0.0-beta.6

**Comment by aldeed** [comment]
Seems like probably the same issue reported here: https://github.com/reactioncommerce/reaction/issues/6231

**Comment by willopez** [comment]
resolved in https://github.com/reactioncommerce/reaction-admin/pull/258
