### ISSUE TITLE
Placeholder in custom taxes rates field inconsistent with calculation

### ISSUE THREAD

**Issue by derBretti** [reactioncommerce/reaction-admin#277]
## Issue Description
The placeholder in custom taxes rates field states "Example: 0.05 means a 5% tax rate", but in the calculation in api-plugin-taxes-rates the tax rate is divided by 100 before it is applied

## Steps to Reproduce
1. Go to settings/tax-settings
2. Add a custom tax with rate 0.05
3. Apply tax rate to a product with a price of $1000
5. Put the product in your cart and proceed to checkout
4. Note that tha tax applied is $0.50 instead of $50

## Possible Solution
Change calculation (inconsistent with behavior in v2)
or
Fix label (better)

### Versions
1.0.0

**Comment by aldeed** [comment]
Agree that label change is the best option here. Moved this issue to admin repo.

**Comment by loan-laux** [comment]
The label has already been updated as part of https://github.com/reactioncommerce/api-plugin-taxes/pull/2. I'd say this one can be closed.

<img width="396" alt="Screen Shot 2021-02-25 at 23 38 52" src="https://user-images.githubusercontent.com/45489203/109207517-a1fceb80-77c2-11eb-8aa0-577d5e584a07.png">
