### ISSUE TITLE
Unable to upload shop logo

### ISSUE THREAD

**Issue by null-ref-0000** [reactioncommerce/reaction-admin#282]
Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE REQUESTS ACCEPTED. For new features, add an issue in our [Request Feature Request](https://github.com/reactioncommerce/reaction-feature-requests) repository.

Are you looking for help with getting started on Reaction? Please visit our [Reaction documentation](https://docs.reactioncommerce.com/reaction-docs/trunk/getting-started-developing-with-reaction).

## Prerequisites
* [X ] Are you running the latest version?

3.0.0-beta.7

* [X ] Are you able to consistently reproduce the issue?
* [X] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description

Unable to upload a shop logo. After uploading a new shop logo via the admin UI, the image is not present in the UI or in emails. 

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. log in as shop owner
2. upload new png image . settings -> shop -> Shop Logos -> click upload new image
3. confirm new image is not displayed in upper left and corner and not in emails. 

## Possible Solution

unknown 

### Versions
(run `npm run version --silent` from your reaction directory)

Running the 3.0.0-beta.7 docker image from docker hub .

**Comment by nomad-lw** [comment]
Hi, was there an update on this issue?

**Comment by null-ref-0000** [comment]
I get this console error when uploading the image

Uncaught (in promise) TypeError: s is not a function

the source in the browser 

```
const {data: {product: e}} = await s();
```
source code

https://github.com/reactioncommerce/reaction-admin/blob/a52ebe985361bd8e8111b2cea9a7b9ab630f88bf/imports/plugins/core/ui/client/components/media/mediaUploader.js#L74

**Comment by kieckhafer** [comment]
@keanesf can you see if this fixes your issue: https://github.com/reactioncommerce/reaction-admin/pull/315

**Comment by ghost** [comment]
Not issue author but I was able to reproduce this before and I attempted to test it today. In attempting to test the fix I did a checkout on admin `trunk`, cherry-picked `9f7c9d1` into the branch, built admin locally with `docker build .` then tagged and pushed a docker image so I could try this in a test environment. Here are my observations:

- No longer seeing promise rejection [mentioned](https://github.com/reactioncommerce/reaction-admin/issues/282#issuecomment-648565954) on June 24
- See a successful POST to the endpoint with request payload `operationName: "CreateMediaRecord"`

But I had some issues:

- Upload button progress indicator continues and appears to timeout after about 20 seconds.
- When the progress indicator stops the logo is not updated.

In my case I already had a static logo URL set if it makes any difference.

**Comment by kieckhafer** [comment]
Can you try removing the static logo URL? There is an order of preference, and the URL is first, so if that is set, the uploaded logo will not appear: https://github.com/reactioncommerce/reaction-admin/blob/trunk/imports/client/ui/components/ShopLogoWithData/ShopLogoWithData.js#L94

If that works, then it seems like Upload button not resetting may be the only remaining issue.

**Comment by ghost** [comment]
I restored to a db backup without the static logo set and attempted uploading again. Though there's a successful post it's followed by a number of request failures I wasn't sure were related. I've captured a motion graphic here reproducing:

![out](https://user-images.githubusercontent.com/65664227/91092107-1aef7f00-e68a-11ea-902a-e26824de9789.gif)

And here's the error being thrown repeatedly while the progress indicator is doing its thing:

```
{"errors":[{"message":"Variable \"$productId\" of required type \"ID!\" was not provided.","locations":[{"line":1,"column":15}],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["GraphQLError: Variable \"$productId\" of required type \"ID!\" was not provided.","    at _loop (/usr/local/src/app/node_modules/graphql/execution/values.js:92:17)","    at coerceVariableValues (/usr/local/src/app/node_modules/graphql/execution/values.js:119:16)","    at getVariableValues (/usr/local/src/app/node_modules/graphql/execution/values.js:48:19)","    at buildExecutionContext (/usr/local/src/app/node_modules/graphql/execution/execute.js:184:61)","    at executeImpl (/usr/local/src/app/node_modules/graphql/execution/execute.js:89:20)","    at Object.execute (/usr/local/src/app/node_modules/graphql/execution/execute.js:64:35)","    at /usr/local/src/app/node_modules/apollo-server-core/dist/requestPipeline.js:241:48","    at Generator.next (<anonymous>)","    at /usr/local/src/app/node_modules/apollo-server-core/dist/requestPipeline.js:8:71","    at new Promise (<anonymous>)"]}}}]}
```
