### ISSUE TITLE
New Shop manager not visible in list of accounts

### ISSUE THREAD

**Issue by null-ref-0000** [reactioncommerce/reaction-admin#283]
Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE REQUESTS ACCEPTED. For new features, add an issue in our [Request Feature Request](https://github.com/reactioncommerce/reaction-feature-requests) repository.

Are you looking for help with getting started on Reaction? Please visit our [Reaction documentation](https://docs.reactioncommerce.com/reaction-docs/trunk/getting-started-developing-with-reaction).

## Prerequisites
* [X] Are you running the latest version?

3.0.0-beta.7

* [X ] Are you able to consistently reproduce the issue?
* [X ] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description

New shop manager not visible in the admin UI. Shop manager not able to see owner when logged in to UI. 

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. logged in as an owner
2. add a new shop manager
3. shop manager accepts invite and logs in the UI
4. owner not able to see to see shop manager in list of accounts
5. shop manager not able to see owner in list of accounts

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug

### Versions
(run `npm run version --silent` from your reaction directory)

running 3.0.0-beta.7 docker image .

**Comment by loan-laux** [comment]
Thanks for the bug report, @keanesf! This will be fixed as part of #276.
