### ISSUE TITLE
Uncaught promise error when permissions are not correct

### ISSUE THREAD

**Issue by brent-hoover** [reactioncommerce/reaction-admin#284]
## Issue Description
When navigating to either Order or Product screens receive this error in the browser console. No message is shown to the user, just a stuck waiting screen:

```
Uncaught (in promise) Error: GraphQL error: Access Denied
```

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Use a user who doesn't have the proper permissions (I am using a 2.x migrated user)
2. Navigate to Orders
3. Observe the error

## Possible Solution
This error should be caught and a proper error message should be displayed

### Versions
v3.0.0 beta 7

**Comment by loan-laux** [comment]
How do we want to solve this? Should we show a full-screen error message saying that the user doesn't have the required permissions?
