### ISSUE TITLE
Get deprecation warning when using latest version of admin

### ISSUE THREAD

**Issue by brent-hoover** [reactioncommerce/reaction-admin#288]
## Issue Description
Get tons and tons of these in the logs
```
 WARN Reaction: Using deprecated field `price` on type `Product`, please use field `pricing` instead.
```

## Steps to Reproduce
1. Browse "Products" in admin while watching api logs

## Possible Solution
Use `pricing`

### Versions
v3.0.0 beta-v7

**Comment by loan-laux** [comment]
I'm taking on this one if you guys don't mind.
