### ISSUE TITLE
Get error when doing a bulk operation on tags

### ISSUE THREAD

**Issue by brent-hoover** [reactioncommerce/reaction-admin#289]
## Issue Description
When performing an operation on multiple tags you get the following error from the API server:
```
api_1    | 07:49:53.958Z ERROR Reaction: Slug everlast is already in use (errorId=ckbhmm2li000d0iqsdq2af5sj)
api_1    |   path: [
api_1    |     "updateTag"
api_1    |   ]
api_1    |   --
api_1    |   stack: ReactionError: Slug everlast is already in use
api_1    |       at Object.updateTag (file:///usr/local/src/app/node_modules/@reactioncommerce/api-plugin-tags/src/mutations/updateTag.js:93:13)
api_1    |       at runMicrotasks (<anonymous>)
api_1    |       at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

## Steps to Reproduce
1. Navigate to "Tags"
1. Select multiple tags
1. Select an operation (e.g. make hidden)
1. Observer error in api logs and operation does not appear to complete

## Possible Solution
It looks like this may be doing an insert rather than a update?

### Versions
v3.0.0 beta7

**Comment by jrw421** [comment]
Hi @zenweasel! We weren't able to reproduce this bug, so I'll be closing it out. Please feel free to reopen another issue with detailed steps should you continue to see this on your end. Thanks!
