### ISSUE TITLE
Product variant form not showing "fulfillment" control

### ISSUE THREAD

**Issue by ilichh1** [reactioncommerce/reaction-admin#296]
## Prerequisites
* [*] Are you running the latest version?
* [*] Are you able to consistently reproduce the issue?
* [*] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
I followed the getting started guide for the reaction development platform; all the docker containers start and I'm able to login in to the admin dashboard to create my first product (and its respective variant). I'm also able to login into my storefront (https://github.com/reactioncommerce/example-storefront) but when I'm at checkout, in the "2. Choose a shipping method" section, a message saying "No fulfillment methods" appears. I'm stuck there.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Followed steps to get started with reaction on development mode: https://github.com/reactioncommerce/reaction-development-platform#getting-started
2. Started running `make`
3. Create first shop after `make` is done
4. Create product and product variant
5. Search for "fulfillment" control on product form

### Versions
Result of `npm run version --silent` in path `./reaction-development-platform/reaction-admin`
```
3.0.0-beta.7
```

**Comment by ghost** [comment]
@ilichh1 Before you can checkout you'll need to access admin and (1) add a fulfillment method and (2) add a payment method. Then in your cart go back to step one and then save it for the form to update so you can proceed.

**Comment by Akarshit** [comment]
The solution pointed above does the trick.
