### ISSUE TITLE
Menu labels do not load

### ISSUE THREAD

**Issue by delagroove** [reactioncommerce/reaction-admin#299]
## Prerequisites
* [X ] Are you running the latest version?
* [X ] Are you able to consistently reproduce the issue?
* [ X] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
menu labels do not load on first load. must click somewhere or refresh to reveal

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. log in to the admin
2. wait until it loads
3. observe the labels in the left do not appear

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug

### Versions
3.8.X

**Comment by willopez** [comment]
closing is favor of https://github.com/reactioncommerce/reaction-admin/issues/300
