### ISSUE TITLE
Nav Titles Disappearing on Refresh

### ISSUE THREAD

**Issue by martavis** [reactioncommerce/reaction-admin#300]
Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
This issue is for `reaction-admin` for operators. When refreshing any page, the nav's titles disappear. The issue can be seen on this YouTube link: https://youtu.be/qgYkQfDmVSU

## Steps to Reproduce
1. Go to any page
2. Click browser's refresh button
3. Observe no nav titles

### Versions
From the admin's "System Information" page:

![image](https://user-images.githubusercontent.com/47053705/86194571-ad98f500-bb03-11ea-9e0d-a1e23af783bc.png)

**Comment by good-commerce** [comment]
we are reporting this issue is gone in 3.9.0 by some of our devs. @martavis are you still experiencing this?

**Comment by martavis** [comment]
Thank you for checking with me but I decided to go another route, so I can't verify this for you.

**Comment by ghost** [comment]
@good-commerce yes it's still an issue in the most recent beta but cosmetic and easy to work-around by navigating once the page has loaded the i18n strings.

**Comment by Akarshit** [comment]
Most probably related to #309

**Comment by Akarshit** [comment]
Closed via #341
