### ISSUE TITLE
Unstable Accounts page in Admin portal

### ISSUE THREAD

**Issue by hasan-synavos** [reactioncommerce/reaction-admin#305]
We have followed the [Reaction Development Platform](https://docs.reactioncommerce.com/docs/installation-reaction-platform) to install Reaction.

## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? 

## Issue Description
In Admin > [Accounts](http://localhost:4080/accounts), the account section is not stable. Page needs to be refreshed multiple times to be displayed properly. However, most of the time it remains a white space.

Please see this [screenshot](https://imgur.com/a/T5YjsWa)

## Steps to Reproduce
1. Login to Reaction Admin and go to Accounts
2. Accounts section is often displayed as white space

## Possible Solution
All the pages should be stable and should be displayed properly all the time.

## System information
We are getting this error on multiple systems:
* MAC OS Catalina
* Ubuntu 20.04 LTS

**Comment by kieckhafer** [comment]
Thanks for the reported issue, @hasan-synavos.

The `reaction-development-platform` repository is used to bootstrap the project and get it up and running, but issues regarding the API, Admin, Storefront, or anything outside the initial build are better suited in their respective project repositories.

I'm going to move this issue to the `reaction-admin` repo. It's possible it's an API issue and should instead be in the API repository, but for now `admin` seems like a better place until it's further investigated.

**Comment by Akarshit** [comment]
Hey @hasan-synavos 
I was trying to reproduce this one but everything seems to be working for me. Is there something specific that you did that might have triggered this one? Would be helpful to know to start working on this one.

**Comment by loan-laux** [comment]
I think this might have been before the complete refactor of the Accounts page. It used to use DDP but has been rewritten to use GraphQL recently.
