### ISSUE TITLE
Left side bar labels are not visible

### ISSUE THREAD

**Issue by tanzeelazad95** [reactioncommerce/reaction-admin#310]
We have followed the [Reaction Development Platform](https://docs.reactioncommerce.com/docs/installation-reaction-platform) to install Reaction

## Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you able to consistently reproduce the issue?
* [ ] Are you logged in as a [Admin](http://localhost:4080)

## Issue Description
"In the admin portal, the navigation links in left side bar are not visible all the time. We need to refresh 
page multiple times to see the labels."
[Screenshot](https://imgur.com/a/sFMGvGM)
## Steps to Reproduce
1. Login to reaction [member's dashboard](http://localhost:4000/)
2. And you will observe that navigation links in left side bar are not visible all the time

## Possible Solution
The navigation links should be visible all the time

## System information

- MAC OS Catalina
- Ubuntu 20.04 LTS

**Comment by kieckhafer** [comment]
Thanks for the reported issue, @tanzeelazad95.

The `reaction-development-platform` repository is used to bootstrap the project and get it up and running, but issues regarding the API, Admin, Storefront, or anything outside the initial build are better suited in their respective project repositories.

I'm going to move this issue to the `reaction-admin` repo.

**Comment by kieckhafer** [comment]
@tanzeelazad95 please see my answer here: https://github.com/reactioncommerce/reaction-admin/issues/309#issuecomment-678536373

![image](https://user-images.githubusercontent.com/4482263/90939327-a3d79380-e3c8-11ea-9fc9-b9b04ffc7ec9.png)

This is an issue with translations, be sure you are loading at least english translations as a fallback.

**Comment by ghost** [comment]
Sidebar labels disappearing in Beta 9 is not present. @tanzeelazad95 could you confirm please?

**Comment by balibebas** [comment]
@kieckhafer I believe this issue should be closed unless someone else is able to reproduce the issue in Beta 9.

**Comment by loan-laux** [comment]
@balibebas I'm still experiencing them with the latest trunk.

**Comment by balibebas** [comment]
Thanks I'm seeing it again now too. Given the issue is due to a race condition it is intermittent. I was it's also a duplicate of #300 and should probably be closed to keep the issue count in this repo down.

**Comment by ghost** [comment]
Thanks I'm seeing it again now too. Given the issue is due to a race condition it is intermittent. I noticed this issue also duplicates #300 and should be closed. @tanzeelazad95 could confirm this issue is a duplicate and close it please?

**Comment by tanzeelazad95** [comment]
@balibebas yes the issue is duplicate to https://github.com/reactioncommerce/reaction-admin/issues/309. So I am closing the issue.
