### ISSUE TITLE
Logo is not uploading from the reaction admin

### ISSUE THREAD

**Issue by hamza0200** [reactioncommerce/reaction-admin#312]
We have followed the [Reaction Development Platform](https://docs.reactioncommerce.com/docs/installation-reaction-platform) to install Reaction.

## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?

## Issue Description
When we are trying to upload logo from the [admin shop](http://localhost:4080/settings/shop) the logo is not uploading. We have tried to stop/start docker and  even tried to reset cache multiple times but it doesnot work at all. It is giving different errors on different browser's console, please open below screenshots for viewing errors:

* [Chrome console errors](https://imgur.com/a/35gNR7e)
* [Firefox console errors](https://imgur.com/a/But1w2D)

## Steps to Reproduce
1. Login to reaction admin dashboard
2. Navigate to Settings > Shop > Shop Logos
3. Upload logo

## Possible Solution
The logo should upload 

## System information
We are getting this error on multiple systems:
* MAC OS Catalina
* Ubuntu 20.04 LTS

**Comment by kieckhafer** [comment]
Issue 143, referenced in the comment above, has been moved to the `example-storefront` repository

https://github.com/reactioncommerce/example-storefront/issues/720

**Comment by kieckhafer** [comment]
Moving this issue to `reaction-admin`

**Comment by balibebas** [comment]
@hamza0200 Could you confirm you're also having issues removing the static logo, once set? I hit this issue while testing https://github.com/reactioncommerce/reaction-admin/issues/282 but ended up using a workaround to get past it. Given the state of the UI my expectation would be that the Static Logo URL could be cleared and the field then saved but unfortunately I can't get that working. Also, if it's of any help, I think a workaround for getting the email logos to display properly while https://github.com/reactioncommerce/reaction-admin/issues/282 and any logo-related issues are outstanding/unresolved is to override `shop-logo.png` in `reaction/public/resources/email-templates`.
