### ISSUE TITLE
Admin can login as regular user

### ISSUE THREAD

**Issue by hasan-synavos** [reactioncommerce/reaction-admin#314]
We have followed the [Reaction Development Platform](https://docs.reactioncommerce.com/docs/installation-reaction-platform) to install Reaction.

## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? 

## Issue Description
An admin can login to the [regular user portal](http://localhost:4000) and the system considers him as a regular user in this case.

## Steps to Reproduce
1. Go to regular user portal and click on Sign In
2. Enter admin user credentials and click on Sign In button 
3. Admin user is signed in as a regular user

## Possible Solution
An admin user should **not** be allowed to login as a regular user.

## System information
We are getting this error on multiple systems:
* MAC OS Catalina
* Ubuntu 20.04 LTS

**Comment by kieckhafer** [comment]
Hey @hasan-synavos,

Can you go more in depth into what you mean a manager should not be allowed to login as a "regular user"?

The link you provided goes to the Example Storefront, are you saying a manager should not be allowed to login as a "customer" on the storefront?

**Comment by ghost** [comment]
Related #311. @hasan-synavos could you please follow-up or close these issues?

**Comment by hasan-synavos** [comment]
@kieckhafer 
By "regular user", I meant a customer who signs up on storefront... and by "admin user" who signs up and uses admin portal. The behavior that we have observed is that a "regular user" (or customer) can use his/her credentials on the admin portal and can successfully sign in & use the admin portal unrestricted. Similarly, an admin user can go to the storefront and he/she can perform all the tasks of a customer.

**Comment by ghost** [comment]
The identity service is used by both Admin and the Storefront. Once the admin/manager is created via the Admin they have the ability to login and use the Example Storefront. Syed, could you help explain why this behavior is unexpected?

**Comment by hamza0200** [comment]
> The identity service is used by both Admin and the Storefront. Once the admin/manager is created via the Admin they have the ability to login and use the Example Storefront. Syed, could you help explain why this behavior is unexpected?

@balibebas please refer the ticket #311 and comment [here](https://github.com/reactioncommerce/reaction-admin/issues/311#issuecomment-689451680).
