### ISSUE TITLE
Refresh Sitemap GraphQL Access Error

### ISSUE THREAD

**Issue by ghost** [reactioncommerce/reaction-admin#318]
## Prerequisites
* [x] Are you running the latest version? Yes, `beta.9` release.
* [x] Are you able to consistently reproduce the issue? Every time.
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
Clicking Refresh Sitemap results in a GraphQL Access Error when using Store Owner.

<img width="752" alt="Screen Shot 2020-09-05 at 08 25 47" src="https://user-images.githubusercontent.com/65664227/92292859-09dc2300-ef52-11ea-9521-23a295455363.png">

The error is **Error: GraphQL error: Access Denied**.

<img width="606" alt="Screen Shot 2020-09-05 at 08 34 45" src="https://user-images.githubusercontent.com/65664227/92292988-af8f9200-ef52-11ea-8963-259b1d2cd265.png">

Response from server:

```json
{"errors":[{"message":"Access Denied","locations":[{"line":2,"column":3}],"path":["generateSitemaps"],"extensions":{"code":"FORBIDDEN","exception":{"eventData":{},"error":"access-denied","isClientSafe":true,"reason":"Access Denied","details":{},"stacktrace":["ReactionError: Access Denied","    at Object.context.validatePermissions (file:///usr/local/src/app/node_modules/@reactioncommerce/api-core/src/util/buildContext.js:49:27)","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (internal/process/task_queues.js:94:5)","    at async Object.generateSitemaps (file:///usr/local/src/app/node_modules/@reactioncommerce/api-plugin-sitemap-generator/src/mutations/generateSitemaps.js:15:3)","    at async generateSitemaps (file:///usr/local/src/app/node_modules/@reactioncommerce/api-plugin-sitemap-generator/src/resolvers/Mutation/generateSitemaps.js:20:3)"]}}}],"data":null}
```

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Log in as store manager for existing store
2. Navigate to Settings > Shop
3. Scroll to the bottom of Shop settings
4. Click Refresh Sitemap
5. Observe error pictured above in Developer Console

## Possible Solution
Not clear why it's occurring as the `generate/sitemap` job is backgrounded anyway. Also worth noting the following mutation does not produce an error when issued from the GraphQL Playground using the shop owner's Authorization header:

```graphql
mutation GenerateSitemaps {
  generateSitemaps(
    input: {
      shopId: "cmVhY3Rpb24vc2hvcDphU1lHMnhtZkNGRkZrampCZQ=="
    }
  ), {
    wasJobScheduled
  }
}
```

### Versions
3.9.0

**Comment by loan-laux** [comment]
It seems to be because the `shopId` is not passed to the `generateSitemaps` mutation. I'll fix this.
