### ISSUE TITLE
Email panel causes Admin instances to crash

### ISSUE THREAD

**Issue by brent-hoover** [reactioncommerce/reaction-admin#325]
## Issue Description
The email log in the email settings panel does a naive subscribe to the collection which pulls down all records one-by-one. When running in production with a lot of records in this collection, this causes a memory to leak until finally the instance crashes due to OOM.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Have more than 50k records in the email collection
2. Bring up an instance
3. Observe that once you open the Settings/Email panel memory usage starts going up and never goes down until reaches whatever the maximum is.

## Possible Solution
Rewrite this panel to use a paginated query. We just removed it in production to stabilize the instances.

### Versions
Version 3.0.0 beta 9

**Comment by Akarshit** [comment]
@nnnnat I was looking into ways to solve this. This is what I have so far:
The query fetches all emails and is used by `SortableTable`, which expects all of the data to be present. This is used for filtering and pagination. If we were to change this, we would have to implement a few things like:
1. Pagination while fetching the query on the server.
2. Filtering/search on the server.
3. Modifying the `SortabeTable` to handle this new type of stream.

Wanted to get a confirmation if this seems like a good plan to go forward with. Another option is to make it a GQL query and do the same things as above.

**Comment by brent-hoover** [comment]
My .02. I think this is one of the last remnants of Meteor in admin and is probably a good candidate for a GQL query. This should be the standard pattern by now I would think

**Comment by nnnnat** [comment]
Yeah I agree with @zenweasel here. We should try to move this to a GQL query and follow the same pagination/filtering patters we have for things like products and orders (hopefully minimize the amount of modifications to `SortableTable`). Probably not a small lift but the patterns should exist now @Akarshit if you want to take this on.

**Comment by loan-laux** [comment]
I'm taking on this one if you guys don't mind. Already started to implement the paginated query on `api-plugin-email`. PRs coming soon.

**Comment by loan-laux** [comment]
Thanks for assigning me, @nnnnat. Can you move this to `In Progress` on the `Bugs & Stability Improvements` board? Just to satisfy my PTSD and show some progress on that loading bar. 😄

**Comment by loan-laux** [comment]
@nnnnat, feel free to check out my two PRs when you have some time:

https://github.com/reactioncommerce/api-plugin-email/pull/6
https://github.com/reactioncommerce/reaction-admin/pull/350

**Comment by nnnnat** [comment]
@loan-laux I got you. Someone will get these reviewed hopefully next week. Thank you for helping out here, very much appreciated.
