### ISSUE TITLE
Invited shop manager does not have acces to shop

### ISSUE THREAD

**Issue by ivanpetrus** [reactioncommerce/reaction-admin#330]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
Invited shop manager does not see shop details after login.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Create shop
2. Add email settings
3. Invite new shop manager
4. Register new shop manager
5. Verify email
6. Login to reaction commerce admin panel
7. Result, just empty page without shop name and navigation, when click on Orders, you will got http://localhost:4080/undefined/orders, but when i put shop id, i was able to create product.
![image](https://user-images.githubusercontent.com/21004743/95253221-c31a6b00-0826-11eb-8ee3-d27824f38377.png)
 
![image](https://user-images.githubusercontent.com/21004743/95902558-a5f11980-0d9d-11eb-87c4-b20e9774f889.png)

## Possible Solution
Shop manager should be able to see shop details

### Versions
reactioncommerce/example-storefront v4.0.0,
reactioncommerce/identity v3.3.0,
reactioncommerce/reaction v3.10.0
reactioncommerce/admin v3.0.0-beta.10

**Comment by loan-laux** [comment]
Can reproduce, and can confirm that this is because the created account object isn't getting its `adminUIShopIds` array populated. I will PR a fix.
