### ISSUE TITLE
Product can be published and displayed on storefront with only a variant attribute

### ISSUE THREAD

**Issue by jrw421** [reactioncommerce/reaction-admin#342]
## Prerequisites
* [X] Are you running the latest version?
* [X] Are you able to consistently reproduce the issue?
* [X] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
Within reaction-admin a user can create, save, and publish a product without adding any information except ticking `Include in sitemap` and adding a variant attribute. The product should require at least a title and a price before allowing the user to publish.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Navigate to `Create product`
2. Don't enter any information, with the exception of ticking `include in sitemap`
3. Press save and then publish
4. You should see the error `GraphQL error: Some Products could not be published to the Catalog. Make sure the parent product and its variants and options are visible`
5. Add an attribute title to a variant and save
6. Make both the variant and the product visible
7. Press publish
8. Navigate to the example-storefront
9. You should see an empty product with a price of $0

## Possible Solution
Make at least the title and price required fields.

**Comment by nnnnat** [comment]
@jrw421 has this issue been resolved?

**Comment by jrw421** [comment]
Yes, I'll mark as closed.
