### ISSUE TITLE
Navigation page doesn't render the navigation tree anymore

### ISSUE THREAD

**Issue by loan-laux** [reactioncommerce/reaction-admin#359]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
The `Navigation` page displays a blank area instead of the navigation tree, making it impossible to see or edit the navigation tree.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Go to the `Navigation` page.
2. See that the right part is blank, which is where the navigation tree should be shown.

## Possible Solution
I had already fixed a bug with the same symptom [here](https://github.com/reactioncommerce/reaction-admin/pull/278). However, this time, it doesn't seem that the solution will be anything related to this previous one. One important note: the `react-sortable-tree` package looks like it hasn't had a release since August 2020, and seems pretty abandoned given the queue of PRs and issues.

### Versions
`3.0.0-beta.13`

**Comment by MohanNarayana** [comment]
Hi @loan-laux. I am able to see the items under the Add Navigation Item button but not the hierarchy tree on the right of it. Is this what you see too? Also, the drag and drop does not respond.

**Comment by loan-laux** [comment]
Yep @MohanNarayana. These are exactly the symptoms I was referring to. Still puzzled as to what causes this, but I would really suspect something with `react-sortable-tree`, as this dependency has already caused the same exact issue earlier.

**Comment by MohanNarayana** [comment]
@loan-laux I can see the tree data come through and i can see the same data render on a sandbox page. I tried updating some packages (react-sortable-tree, react-dnd-html5-backend and react-dnd) but no luck. Do you think there are any other other package that I can try updating? Thanks

**Comment by loan-laux** [comment]
@MohanNarayana no idea, tbh. But `react-sortable-tree` hasn't been updated since August 2020, with a few unanswered issues asking if the project is dead. Not a good sign. I feel like a transitive dependency might be causing this. But it's hard to know.

**Comment by MohanNarayana** [comment]
The project is definitely abandoned judging by [this](https://github.com/frontend-collective/react-sortable-tree/issues/862) issue with no response from the core team.

**Comment by delagroove** [comment]
can you try using react-sortable-tree-w for this? looks more active
https://www.npmjs.com/package/react-sortable-tree-w

**Comment by nosferatu500** [comment]
Hi guys,

If you still have this problem, you can try my fork. I had the same problem and fork the original package to solve it.

yarn add @nosferatu500/react-sortable-tree

**Comment by loan-laux** [comment]
@delagroove @nosferatu500 I tried both `react-sortable-tree-w` and `@nosferatu500/react-sortable-tree`. Both also fail silently like the original `react-sortable-tree`.

**Comment by nosferatu500** [comment]
@loan-laux hmm ... Let me check it out over the weekend. If the reason is this module, I can try to fix it.

**Comment by nosferatu500** [comment]
@loan-laux 
how can I build your project? 

`docker-compose -f <dev-file> up` ?

**Comment by loan-laux** [comment]
@nosferatu500 yes, but you'll need to have the Reaction Commerce API running too, since this is the admin UI for that API.

The easiest way is to clone the [`reaction-development-platform`](https://github.com/reactioncommerce/reaction-development-platform). Run the `make` command as indicated in the `README`, which will clone all of Reaction's sub-projects and start the containers (essentially running the `docker-compose` commands for you).

Once you've done that, enable development mode for the admin UI sub-project by running `make dev-link-reaction-admin`. Then, restart your `reaction-admin` component. Now, any changes made to the code under `reaction-admin` will take effect, and you can try stuff out.

Thanks for taking the time! I appreciate it.

**Comment by loan-laux** [comment]
I've tried a bunch of things like move the `DndProvider` closer to the `NavigationItemList` component. No dice. I'm really stuck as to why this is not rendering. The fact that no error is thrown is also not helping.

**Comment by DmaKill** [comment]
@loan-laux  I have fixed the error in this [PR](https://github.com/reactioncommerce/reaction-admin/pull/382), but the pipelines have failed 
![Navigation](https://user-images.githubusercontent.com/5446712/126556365-0097c374-15cc-44a6-8240-5238359107f6.gif)

**Comment by delagroove** [comment]
fixed in 3.0.0-beta19
https://github.com/reactioncommerce/reaction-admin/pull/382#issuecomment-892724447
