### ISSUE TITLE
Product metadata breaking admin panel

### ISSUE THREAD

**Issue by blackspider1994** [reactioncommerce/reaction-admin#374]
While creating product in reaction admin , Screen goes white when start typing in key filed under meta data section in product create form.

Steps to Reproduce

1. Login to admin 
2. Go to create product
3. Scroll down to metadata form
4. Enter key (breaks upon entering 3 values)

products package version 1.0.2
reaction-admin version 3.0.0-beta.13
reaction-api version 3.11.1

![image](https://user-images.githubusercontent.com/17843545/122547152-2b258000-d049-11eb-8273-2249f31840ee.png)

**Comment by loan-laux** [comment]
@blackspider1994 thanks for reporting this issue. Can you please strip out the unnecessary bits from the issue template and include the browser console logs that you're getting when the page goes blank?
