### ISSUE TITLE
initApollo.js: WebSocket is closed before the connection is established.

### ISSUE THREAD

**Issue by quano1** [reactioncommerce/reaction-admin#383]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
After login as admin. Constantly get this message on admin page: 'WebSocket connection to 'ws://localhost:3000/graphql' failed: WebSocket is closed before the connection is established.'

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. start all containers
2. login admin
3. refresh the page
4. Observe the issue

## Possible Solution
A solution from: https://github.com/hasura/graphql-engine/issues/4509#issuecomment-759838030

[initApollo.js](https://github.com/reactioncommerce/reaction-admin/blob/trunk/imports/plugins/core/graphql/lib/helpers/initApollo.js#L99)

```
new WebSocketLink({
      uri: graphQlApiUrlWebSocket,
      options: {
        reconnect: true, // auto-reconnect
        lazy: true, // <--- THIS LINE
        connectionParams: {
          authToken: localStorage.getItem("Meteor.loginToken")
        }
      }
    }),
```

### Versions
3.11.1

**Comment by j2l** [comment]
Even after fixing `initApollo.js` I get an empty profile for the admin user.
In console:
`WebSocket connection to 'ws://localhost:3000/graphql' failed: WebSocket is closed before the connection is established.`
