### ISSUE TITLE
Confusing permissions settings in dashboard

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction-admin#95]
### Expected behavior
Every permission setting should have a clear label

### Actual Behavior
Not sure what I would be giving permissions for the two subitems for "Orders"
![dumb_product](https://cloud.githubusercontent.com/assets/72819/26134081/ad0739f6-3ade-11e7-89be-6b82bca1fe64.png)

### Steps to Reproduce the Behavior
1. Manage a user

### Versions
```
Node: 7.10.0
NPM: 4.2.0
Meteor Node: 4.8.2
Meteor NPM: 4.5.0
Reaction CLI: 0.8.2
Reaction: 1.2.0
Reaction branch: release-1.2.0
Docker: 17.03.1-ce
```

**Comment by brent-hoover** [comment]
Closing as this refers to an old version of the UI
